name: Pipeline de CI (Construcción y Pruebas)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  construir-y-probar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Configurar el entorno de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: 3. Instalar dependencias (Build)
        run: npm install

      - name: 4. Ejecutar pruebas (Test)
        run: npm test
